### ISSUE TITLE
Dev commands left in production

### ISSUE THREAD

**Issue by PotatoPresident** [NandorKovacs/MultiSleep#2]
You have your dev commands in the latest releases. This is a major security issue for servers. I highly recommend wrapping your dev commands with
```java
if (FabricLoader.isDevelopmentEnvironment()) {
```

**Comment by NandorKovacs** [comment]
thanks, ill fix that now

also thanks for the code snippet

**Comment by NandorKovacs** [comment]
I archived the old build on curseforge and released a fixed one, which should be approved any minute now.
