### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by LeotomasMC** [NandorKovacs/MultiSleep#3]
it seems you released a build with a backdoor in it to curseforge.
https://github.com/NandorKovacs/MultiSleep/blob/b11d352d3bf4ba98993e14642126ba36db5f08c9/src/main/java/net/roaringmind/multisleep/MultiSleep.java
it seems you tried to remind yourself to not release a build with it enabled, but either you intentionally left it in, or forgot to remove it. not sure why you need a command to op yourself, as you should have a server console open which you could op yourself from. the other command is reasonable, and does have a permission level so it could probably even be left in, but an op yourself command with no requirements is asking for problems.

**Comment by NandorKovacs** [comment]
ill fix that in a few minutes, sorry

i couldnt find a way to use the server console when running the client from gradle in a development environement, thats the only reason it even exists

**Comment by NandorKovacs** [comment]
The build is archived now, and a new one is uploaded and will be approved by curseforge any minute now.

Thanks for bringing my attention to this
